version: '3.8'

services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
    volumes:
      - bookjs_data:/app/data
    environment:
      TZ: Asia/Shanghai
      NODE_ENV: production
    ports:
      - "770:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  bookjs_data:
    driver_opts:
      type: nfs
      o: addr=nfs.example.com,rw
      device: ":/path/to/data"

networks:
  default:
    driver: overlay
    attachable: true
