version: '3'

services:
   book-js:
      deploy:
        replicas: 1
        restart_policy:  # Swarm 模式专用重启策略
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.5'
            memory: 512M
      image: ${IMAGE_NAME}:${IMAGE_TAG}
      volumes:
         - $PWD/data/bookjs/public:/book_js/public
      environment:
         - TZ=Asia/Shanghai
         - RUN_ENV=dev
         - MAX_BROWSER=3
         - PORT=80
      ports:
         - "770:80"
      command: ["tail", "-f", "/dev/null"]
