version: '3.8'

services:
  app:
    image: uhub.service.ucloud.cn/xpan/book-js:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback  # 添加失败自动回滚
        monitor: 60s  # 监控更新状态的时间窗口
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5  # 增加重试次数
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
        reservations:
          cpus: '0.1'
          memory: 256M
    volumes:
      # 简化卷配置，首先确保基本功能正常
      - /data/bookjs:/app/data
    environment:
      TZ: Asia/Shanghai
      NODE_ENV: production
      LOG_LEVEL: debug  # 改为 debug 级别以获取更多信息
      # 应用连接信息
      APP_PORT: 3000
      DATA_DIR: /app/data
    ports:
      - "770:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  # 增加启动宽限期
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # 确保有 /tmp 写入权限
    tmpfs:
      - /tmp

# 简化网络配置，使用默认网络
networks:
  default:
    driver: overlay
    attachable: true