name: BookJS CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_SERVICE }}/xpan/book-js

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 新增时间戳生成步骤
      - name: Generate timestamp tag
        id: timestamp
        run: |
          TAG=$(TZ=Asia/Shanghai date +'%y%m%d-%H%M%S')
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          # 使用raw类型定义标签
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.timestamp.outputs.tag }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            # 新增镜像引用验证
            IMAGE_REF="${{ env.IMAGE_NAME }}:${{ needs.build-push.outputs.image_tag }}"
            
            # 严格格式验证
            if [[ ! "$IMAGE_REF" =~ ^[a-z0-9.-]+(/[a-z0-9_-]+){2}:[a-zA-Z0-9_.-]+$ ]]; then
              echo "##[error] Invalid image reference: $IMAGE_REF"
              exit 1
            fi

            # 带格式检查的替换
            sed -i "s|image:.*|image: ${IMAGE_REF}|" docker-compose.prod.yaml
            
            # 显式指定detach模式
            docker stack deploy \
              --compose-file docker-compose.prod.yaml \
              --with-registry-auth \
              --detach=false \
              bookjs_stack
